Feature 4
ClubCedille/crabe-inventaire pull request #14
Opened 2019-07-14 18:49 UTC by jalilbengoufa

- verifier email pour continuer inscription
- payer par paypal son abonnement pour avoir acces au portail
- ajout de middlewares pour que les acces au differentes routes soient bon
- ajout du model et controlleur de transaction
- ajout du model et controlleur de log

2019-07-15 04:18 UTC, notarock requested changes
Je pense que ça serait bon d'avoir un peu de documentation pour que tous le monde puissent suivre.
La plupart des variables d'environnement n'ont pas de valeurs, alors le code plante à plusieurs endroits.

Aussi, est-ce qu'on devrat remettre `develop` comme branche principale ?

2019-07-15 04:18 UTC, notarock commented on .env
> +MAIL_USERNAME=null
Les nouvelles info dans le .ENV devraient se retrouvre dans l'exemple aussi. Ça serait aussi cool de documenter qu'il faut modifier ces variables dans le .env pour que ça fonctionne. Par exemple, je vient de me register et le SMTP ne fonctionne pas sans ces variables. J'avais déjà un compte pour mailtrap.io alors j'ai mis mes infos pour que ca fonctionne :smirk:

2019-07-15 04:26 UTC, jalilbengoufa commented on .env
> +MAIL_USERNAME=null
ouep j'aurais du mettre ca dans la doc et je vais  l'ajouter, mais  mettre les info dans le .env, je ne suis pas trop d'accord. On devrait laisser `master` comme la branche principal avec le code stable et `develop` pour l'ajout des features et bug fix

2019-07-15 04:27 UTC, notarock commented on .env
> +MAIL_USERNAME=null
Dans ce cas, on pourrait mettre `develop` comme branche principale pour encourrager les gens à faire leurs pull-requets sur cette branche plutot que sur `master` comme j'avais fait :)

2019-07-15 04:28 UTC, notarock commented on .env
> +MAIL_USERNAME=null
On fait une pull-request vers `master` lorsqu'on aura rencontrer crabe de nouveaux, tu en penses quoi?

2019-07-15 04:30 UTC, jalilbengoufa commented on .env
> +MAIL_USERNAME=null
oui c'est parfait, comme ca on va savoir que ce qu'on fait dans le `master` va dans la bonne direction.

2019-07-16 03:37 UTC, notarock approved these changes

2019-07-16 03:38 UTC, merged