Feature/6
ClubCedille/crabe-inventaire pull request #21
Opened 2019-08-30 02:22 UTC by waldo121

Gestion de produits et de catégories par les admins.

2019-08-30 17:51 UTC, jalilbengoufa requested changes

2019-08-30 17:51 UTC, jalilbengoufa commented on routes/web.php
> +    Route::resource('products','ProductsController')->only(['index','show']);
Ca doit etre dans le groupe auth verifier, un user doit avoir un compte pour pouvoir voir les  produits

2019-08-30 17:51 UTC, jalilbengoufa commented on app/Http/Controllers/ProductsController.php
> +
Il faudrait peut etre verifier que la categorie existe deja dans la DB avec son id avant de creer un produit pour eviter une erreur pendant la requete sql

2019-08-30 17:51 UTC, jalilbengoufa commented on app/Http/Controllers/ProductsController.php
> +
Paraeil comme la fonction store, verify que la category existe dan la DB

2019-08-30 17:59 UTC, waldo121 commented on app/Http/Controllers/ProductsController.php
> +
C'est vérifié déjà.

2019-08-30 17:59 UTC, waldo121 commented on app/Http/Controllers/ProductsController.php
> +
C'est vérifié déjà.

2019-08-30 18:02 UTC, jalilbengoufa commented on app/Http/Controllers/ProductsController.php
> +
pas faux je l'ai  pas vu

2019-08-30 18:17 UTC, waldo121 commented on routes/web.php
> +    Route::resource('products','ProductsController')->only(['index','show']);
Leur membership doit etre valide aussi pour voir les produits?

2019-08-30 18:18 UTC, jalilbengoufa commented on routes/web.php
> +    Route::resource('products','ProductsController')->only(['index','show']);
oui

2019-09-02 21:37 UTC, notarock approved these changes
Looking good, impliquant que les derniers changements demandés par Jalil soit appliqués.

2019-09-02 22:59 UTC, waldo121 commented
Oops, je ne pensais pas que les trucs de catégorie ont bougé aussi.

2019-09-03 22:26 UTC, jalilbengoufa approved these changes

2019-09-03 22:26 UTC, merged