update payment with paypal to handle errors and save transaction in db
ClubCedille/crabe-inventaire pull request #23
Opened 2019-09-06 21:12 UTC by jalilbengoufa

also make create a different transaction for account activation and product payment

2019-09-06 22:08 UTC, notarock requested changes

2019-09-06 22:08 UTC, notarock commented on app/Product.php
> +    public function updateQuantity($quanityToremove){
updateQuantity enlève la qualité? Je pense que ca serait mieux de lui envoyer `-1` ou bien la renommer `removeQuantity`

2019-09-07 00:29 UTC, jalilbengoufa commented on app/Product.php
> +    public function updateQuantity($quanityToremove){
Je vais la renommer removeQuantity, c'est plus clair

2019-09-07 04:14 UTC, notarock approved these changes

2019-09-07 04:57 UTC, merged