frontend category
ClubCedille/crabe-inventaire pull request #27
Opened 2019-09-07 17:20 UTC by jalilbengoufa

2019-09-07 17:56 UTC, waldo121 commented on routes/web.php
> +                Route::delete('category/{id}', 'CategoryController@destroy');
Le destroy pourrait être bloqué à cause des contraintes de foreign key entre Produit et Category.

2019-09-08 00:50 UTC, jalilbengoufa commented on routes/web.php
> +                Route::delete('category/{id}', 'CategoryController@destroy');
la suppression d'une Category n'est pas blocker par la contrainte entre Produit et Category, mais je vais set la valeur a null dans produit quand la category est supprime.

2019-09-08 01:43 UTC, notarock requested changes

2019-09-08 01:43 UTC, notarock commented on database/migrations/2019_07_16_142826_create_products_table.php
> +            $table->foreign('category_id')
Est-ce nécessaire de définir deux fois le `category_id`?

2019-09-08 01:43 UTC, notarock commented on resources/js/components/categoryComponent.vue
> +    console.log(this.message.length)
Console log

2019-09-08 02:03 UTC, jalilbengoufa commented on database/migrations/2019_07_16_142826_create_products_table.php
> +            $table->foreign('category_id')
oui, sinon ca fonctionne pas, je l'ai esseye

2019-09-08 02:11 UTC, notarock approved these changes

2019-09-08 20:15 UTC, waldo121 approved these changes

2019-09-09 18:53 UTC, merged