Test review app config
ClubCedille/crabe-inventaire pull request #45
Opened 2020-02-22 00:21 UTC by notarock

Ajoute un review sur heroku lors d'une pull request

2020-03-10 18:37 UTC, notarock commented
# Sup vous autres,

Quand vous voulez faire une review de pull request, pesez sur :

![image](https://user-images.githubusercontent.com/25652765/76347195-93c96d00-62dc-11ea-96c9-f51de2c1c747.png)

Et vous allez pouvoir vous login avec le compte:

cedille@etsmtl.net
password: secret

Ces credentials sont littéralemetn hardcodé dans la seed, donc ils vont toujours fonctionner

2020-03-10 19:23 UTC, berbiche commented
#46

2020-03-10 20:26 UTC, mikefaille commented
Ne pas y utiliser un mot de passe comme ça et aussi ne pas utiliser un compte partagé

2020-03-10 21:06 UTC, notarock commented
> 
> 
> Ne pas y utiliser un mot de passe comme ça et aussi ne pas utiliser un compte partagé

La base de donnée est temporaire et utilisé seulement dans le contexte d'une pull-request, alors je ne vois pas le problème à avoir un utilisateur créée automatiquement pour permettre au gens de reviews les changements rapidement et facilement.

Dans l'idéal, on aurait une database dans notre espace de "Test" et notre app se connecterait dessu pour qu'on puisse tester avec nos data déjà présent, mais on a pas ça. 

De plus, le flow de création d'un compte (que l'on devrait refaire à tout les ~pull-requests~ _commits_ sur une pull-request est plutôt long. 

Si tu veux en savoir plus, regarde ceci: 
https://github.com/ClubCedille/crabe-inventaire/blob/develop/database/seeds/UsersSeeder.php#L15
C'est le code qui est utilisé pour générer des utilisateurs lorsque l'on fait la commande `db seed`. C'est le même compte que l'on utilise pour tester localement, et ils y a plusieurs comptes que l'on peut utiliser pour tester avec des permissions différentes.

2020-03-10 21:16 UTC, notarock commented
Oublions pas que `db seed` ne sera jamais utilisé dans un environnement de production

2020-03-10 21:23 UTC, notarock commented
Si c'est un problème, je vais mettre que ça ajoute le compte seulement dans un environnement local et pas dans le review-app. Par contre on va devoir configurer un serveur-mail et le paiement paypal pour que l'on puisse avoir accès au autres features 🤔

2020-03-10 21:25 UTC, mikefaille commented
Je te propose d'utiliser une fonction random dans un mot de passe. Aussi, pense au cas si quelqu'un est mal intentionné peut te faire payer cher la PR.

2020-03-11 23:13 UTC, cguertin14 approved these changes
Puisque le thème de la PR est le deployment sur Heroku et que c'est fonctionnel, j'approuve.

2020-03-11 23:21 UTC, berbiche requested changes
> Puisque le thème de la PR est le deployment sur Heroku et que c'est fonctionnel, j'approuve.

Ouin, mais le site ne charge pas du tout sur Firefox à cause du contenu mixte (page chargée en HTTPS mais ressources chargées en HTTP).

Je préfère que l'on corrige aussi ce problème dans le même PR.

2020-03-11 23:26 UTC, cguertin14 commented
> > Puisque le thème de la PR est le deployment sur Heroku et que c'est fonctionnel, j'approuve.
> 
> Ouin, mais le site ne charge pas du tout sur Firefox à cause du contenu mixte (page chargée en HTTPS mais ressources chargées en HTTP).
> 
> Je préfère que l'on corrige aussi ce problème dans le même PR.

Sure, peu importe.

2020-03-11 23:28 UTC, berbiche commented
Je remarque que même le formulaire est envoyé en HTTP sur le contexte HTTPS :
![image](https://user-images.githubusercontent.com/20448408/76473284-6230ce80-63ce-11ea-8aec-7bb53369ae06.png)

2020-03-12 14:19 UTC, notarock commented
Je vais checker ça en fds pour le https

2020-03-12 21:56 UTC, AXDOOMER submitted a review, later dismissed
Fixez le HTTPS sur Firefox et oubliez pas de squash. Testez si ça fonctionne bien avec Chrome aussi.

2020-04-05 04:32 UTC, notarock commented
J'ai assez bien avancé mais je pense que y'a un problème avec les variables d'env. Genre, le fichier .env est lu et il devrait pas être dans le code. On devrait plutot setter ca dans le ui sur heroku pour pas exposer les variables d'environnement dans le repo.

2020-05-07 01:52 UTC, waldo121 approved these changes

2020-05-10 21:29 UTC, berbiche commented
Est-ce qu'il manque quoique se soit pour merge ce PR @notarock?

2020-05-10 21:32 UTC, notarock commented
> Est-ce qu'il manque quoique se soit pour merge ce PR @notarock?
> 
> Squash + rebase et bon pour merge?

Regler les conflits de merge et c'est bon je pense. Je vais checker pour faire ça ce soir

2020-05-11 21:17 UTC, berbiche approved these changes
Je n'ai plus de problèmes avec HTTPS/HTTP :+1:

2020-05-12 01:13 UTC, jalilbengoufa approved these changes

2020-05-12 14:07 UTC, notarock commented
Il semble encore y avoir un probl'eme avec la db (je ne suis pas capable de me connecter avec le compte)

2020-05-12 21:40 UTC, cguertin14 approved these changes

2020-07-12 20:50 UTC, berbiche commented
Sais-tu pourquoi le build fail?

2020-07-12 20:55 UTC, berbiche commented on app/Providers/AppServiceProvider.php
> +        if(env('APP_ENV') !== 'local') { $url->forceScheme('https'); }
Pas très configurable comme manière de changer le protocole!

2020-07-12 20:57 UTC, berbiche commented
Sinon quel était la motivation pour avoir changé CircleCi pour TravisCI @notarock?

2020-07-12 20:57 UTC, jalilbengoufa commented
> Sais-tu pourquoi le build fail? À regarder les logs, on dirait qu'il manque une variable d'environnement

ouais je regarde ca , j'ai reussi a deploy, il reste les tests

2020-07-12 20:58 UTC, jalilbengoufa commented
> Sinon quel était la motivation pour avoir changé CircleCi pour TravisCI @notarock?

c'est moi qui l'ai changer aucune raison, je voulais juste changer

2020-07-13 01:41 UTC, jalilbengoufa commented
BON ENFIN !

2020-07-13 01:43 UTC, merged